name: energyeffix_app
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
<<<<<<< Updated upstream
=======
  animated_splash_screen: ^1.3.0
  lottie: ^2.7.0
  curved_navigation_bar:  ^1.0.3



  flutter_svg: ^0.22.0
  carousel_slider: ^4.2.1


>>>>>>> Stashed changes

dev_dependencies:
  flutter_test:
    sdk: flutter
<<<<<<< Updated upstream

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
=======
  flutter_launcher_icons: "^0.11.0"  # Downgraded to version 0.11.0
  flutter_app_name: ^0.1.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/energy_effix_logo.png"


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/energy_effix_logo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/energy_effix_logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/energy_effix_logo.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/energy_effix_logo.png"

flutter_app_name:
  name: "EnergyEffix"

flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
>>>>>>> Stashed changes
    - assets/images/
